"""Surface contract. No browser library objects cross this interface."""

from pathlib import Path
from typing import Protocol

from waypoint.ownership import Ownership
from waypoint.schema import Action, Inputs, Observation, Target


class Surface(Protocol):
    capabilities: frozenset[str]
    ownership: Ownership
    event_sink: object

    async def __aenter__(self) -> "Surface": ...
    async def __aexit__(self, *args): ...
    async def observe(self) -> Observation: ...
    async def act(self, action: Action, inputs: Inputs): ...
    async def read(self, target: Target, inputs: Inputs) -> str: ...
    async def wait_ready(self, timeout_s: float): ...
    async def capture(self, directory: Path, name: str) -> list[str]: ...
